name: Maven Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
      java_version:
        description: 'JDK version (8, 11, 17, 21)'
        required: true
        default: '21'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ github.event.inputs.java_version }}
          distribution: 'temurin'

      - run: mvn package -DskipTests
        working-directory: .

      - uses: actions/upload-artifact@v4
        with:
          name: plugin-jar
          path: target/*.jar
          retention-days: 1
